services:
  api:
    image: ${GAR_IMAGE}:dev
    env_file: .env
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONWARNINGS=ignore
      # - TF_CPP_MIN_LOG_LEVEL=2  # Décommenter si vous utilisez TensorFlow pour masquer les warnings C++
    stdin_open: true # Active le mode interactif (équivalent à -i)
    tty: true        # Alloue un pseudo-TTY (équivalent à -t)
    volumes:
      # Monte votre code local dans le conteneur pour le rechargement à chaud
      - ./berlue:/api/berlue
    # Démarre l'API avec le rechargement automatique activé
    command: sh -c "exec uvicorn berlue.api.fast:app --host 0.0.0.0 --port 8000 --reload"
